### ISSUE TITLE
UI nits (umbrella)

### ISSUE THREAD

**Issue by goldsteinsveta** [paritytech/parity-bridges-ui#193]
- [] 🎨 Bridge direction arrow should not be clickable or otherwise interactive. It should not suggest it might be interactive
- [] TransactionStatus card appearance (#108)
- [] TransactionStatusMock should never appear in the history drawer
- [] TransactionStatus card to display Sender and Receiver in the history drawer
- [] TransactionStatus card "modes": add Payload and Human formatting
- [] SelectSender, refactor, add search, knobs and empty states: no extension detected, no accounts found (#168)
- [] 🎨 Connect to wallet Button should be friendlier, related to SelectSender
- [] Amount inputs should have "max amount" button, it should account for fees

**Comment by hbulgarini** [comment]
Adding some others @goldsteinsveta

- [ ]  Is there any missing tooltip? #104 
- [ ]  Error component #176 
- [ ]  Format and apply styles on Estimated Fee.  #171
